### ISSUE TITLE
filter failing with newly loaded elements

### ISSUE THREAD

**Issue by PedroEsperanca** [TheSharpieOne/angular-off-click#26]
filter doesn't work if elements to filter are loaded after this directive

**Comment by TheSharpieOne** [comment]
Probably related to #25.

**Comment by TheSharpieOne** [comment]
So this was a more or less optimization.  Instead of running all of the `querySelectorAll` queries each time a click happened, it would run it when the directive instantiated and when the value of the filter changed.  The side affect is this bug, when you add new elements, they would not have been captured when `querySelectorAll` ran, and unless you touch the value of the filter, `querySelectorAll` will not run again to capture them.

The only other alternative I can think of besides running `querySelectorAll` for all of the instances on each of the clicks (which more than likely slow it down) is to expose a way to trigger `querySelectorAll` to run again.  But that doesn't seem that great.

**Comment by mkoczorowski** [comment]
Not sure, whats the solution here ?

**Comment by RicardoAlmeidaMarques** [comment]
Resolved.

**Comment by austenpayan** [comment]
Any info on how this was resolved? I am coming across this same error when trying to reference a dynamic id in the filter.

e.g. I have an element whos id is being set dynamically - `id="popover-{{ uniqueId }}"` and another element with an off-click-filter of `'#popover-' + uniqueId`. This seems to be the same problem this issue presents.

**Comment by Ricardo-Marques** [comment]
The issue was resolved by caching the filter when the element that is the filter gets rendered, as opposed to caching filters when the element with off-click renders. Your example should work on the latest version.
