### ISSUE TITLE
Issue with dynamically created filters

### ISSUE THREAD

**Issue by zlovin** [TheSharpieOne/angular-off-click#48]
I have a couple of directives in my UI that use angular interpolation for setting an element's id. For some reason, when adding a new element the off click doesn't function properly. [This](https://plnkr.co/edit/et9OOZ6F3DqJ3KyrN3qh?p=preview) plunkr (using 1.0.7) shows the issue. 
Flow:
Click the 'Add Menu button'
Click the button to 'Toggle menu visible'
At this point, clicking on either the upper 'menu' row (the green border one with the visible button) _or_ the blue bordered div where the menu shows up at should not hide the menu. While clicking on the green-bordered element works as intended, clicking in the blue-bordered element closes the menu, which is unintended.

**Comment by TheSharpieOne** [comment]
The issue is with the value passed to `off-click-filter`. You are passing a string when it excepts an expression (no need for `{{}}`). This is why you have to wrap string literals in single quotes (such as `off-click-filter="'*'"`).
With what you passed `'#{{menu.id}}'` it literally adds `#{{menu.id}}` to the filter (no expression parsed).
Change `off-click-filter="'#{{menu.id}}'"` to `off-click-filter="'#'+menu.id"` to get the desired effect.
At this point, it is a documentation issue as it is not clearly pointed out, only inferred by the example passing a string and not showing how to pass a dynamic value.
