### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zlovin** [TheSharpieOne/angular-off-click#49]
This issue occurred when trying to remove an element that was dynamically added. [This](https://plnkr.co/edit/LW4ej5FBuC93uHxjKPvN?p=preview) plunkr demonstrates the issue. For demonstration sake (as seen in #48), the off-click expression on the `<p>` element has been emptied.
Flow:
Click the 'Add Menu button'
Click the button to 'Toggle menu visible'
Click the 'Remove' button in the menu.
Error shows up as 'TypeError: Cannot read property 'length' of undefined' on line 132:
`if (OffClickFilterCache[filter].length > 1) {`

**Comment by simonghales** [comment]
hey @TheSharpieOne I'm also encountering this issue and I think it's because you need to push the latest changes through to bower (sorry I'm not sure what the correct terminology is there.) From the home page of this repo I can see that you updated the /src files 7 days ago, but the /dist files haven't been updated in several weeks. Thanks!

**Comment by zlovin** [comment]
@TheSharpieOne @Ricardo-Marques Could a new release be pushed out, please?

**Comment by TheSharpieOne** [comment]
Released v1.0.8
